version: '3.9'

services:
  api:
    build: ./api
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db: